name: CI

on:
  push:
    branches:
      - master

jobs:
  build-my-react:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./my-react
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: './my-react/.nvmrc'
      - name: Install Dependencies
        run: corepack enable && yarn install
      - name: Run lint
        run: yarn lint
      - name: Run test
        run: yarn test

